# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2560eea7fbec82a0fc50c1d243666fe63cc1d600937f30eb4b4dcff428ece5fb165bbb78dad6f03a7babeb00314422e2f82e4928f45ba4199e773be75a108f5c

test:
  secret_key_base: f8d340b7ca5301ecc01a497d3f06b43d2ee623b806aa5b47bffdb06b9763c71dd767d708630aacf5db78951375f189d5be28f6832b0effb111208d87aca2ee89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
